#!/bin/bash
DATAPATH=${1?}

# The input template - generated by hand, not satisfying constraints
CMR_TEMPLATE=$DATAPATH/placenta_template_anterioralign3_bcmrep.vtk 

# The target - generated by applying an ANTS transformation to the template
CMR_TARGET=$DATAPATH/placenta_template_def_to_target.vtk

# Fit the template to itself - fixes bad triangles
contest \
  -lsq $CMR_TEMPLATE $CMR_TEMPLATE \
  -reg-weight 100 -reg-ss 1 -o template_fix.vtk \
  -mc 20 135 0.25

# Apply procrustes transform to the template - keeps constraints valid
vtkprocrustes template_fix_fit2tmp_bnd.vtk $CMR_TARGET proc.mat
warpmesh template_fix_fit2tmp_bnd.vtk procrustes_template_fix_fit2tmp_bnd.vtk proc.mat
warpmesh template_fix_fit2tmp_med.vtk procrustes_template_fix_fit2tmp_med.vtk proc.mat

# Fit the template to target using lsq and then icp
./contest -lsq ./procrustes_template_fix_fit2tmp_bnd.vtk $CMR_TARGET \
  -reg-weight 10 -reg-ss 1 -o deform_template.vtk \
  -mc 20 135 0.25

./contest -icp ./deform_template_fit2tmp_bnd.vtk $CMR_TARGET \
  -reg-weight 10 -reg-ss 1 -o icp_template.vtk \
  -mc 20 135 0.25


