FIND_LIBRARY(TETGEN_LIBRARY NAMES tet)

IF(TETGEN_LIBRARY)


  GET_FILENAME_COMPONENT(TETGEN_LIB_DIR ${TETGEN_LIBRARY} PATH)

  FIND_PATH(TETGEN_INCLUDE_DIR NAMES tetgen.h PATHS ${TETGEN_LIBRARY})

  INCLUDE_DIRECTORIES(${TETGEN_INCLUDE_DIR})

ENDIF(TETGEN_LIBRARY)
